### PR TITLE
add state-basedSimulation function

### PR DESCRIPTION
**Pull request by lth-qn**

### CODE REVIEW

**Comment by lorenz-halt** [comment]
why did you close it? Are you still working on it?

**Comment by lth-qn** [comment]
Oh sorry, I don't know that will close your version too. I will open it
again
Best regards,
Anh

Am 28.09.2017 15:21 schrieb "Lorenz Halt" <notifications@github.com>:

**Comment by lorenz-halt** [comment]
Please open your notebook and clean all outputs and save it again. Commit the version (without output) and then I will merge it

**Comment by lorenz-halt** [comment]
On second thought I guess, that B and D should have the same structure since they are both multiplied with u. Please verify the structures of A, B, C and D; and do not rely on my (possibly faulty) example matrices. Thanks

**Comment by lorenz-halt** [comment]
not working as expected. Please compare:https://github.com/ipa-lth/jupyter_nb/blob/qn/Simulation_state-based_2ndTask/state-basedSimulation.ipynb

**Pull request closed without merging**
